### ISSUE TITLE
Create Jupyter notebook with workflow overview - Data Processing

### ISSUE THREAD

**Issue by JordiBolibar** [ODINN-SciML/MassBalanceMachine#10]
Create a Jupyter notebook to showcase how to use the model and the full pipeline as an example.

**Comment by JulianBiesheuvel** [comment]
- [ ] (WIP) One notebook that takes WGMS data by default
- [ ] (WIP) One notebook that takes user custom dataset and makes it in the WGMS format and then does the data processing
