### ISSUE TITLE
Investigate if the creation of the environment can be further optimized

### ISSUE THREAD

**Issue by JulianBiesheuvel** [ODINN-SciML/MassBalanceMachine#43]
See if it can be done in fewer steps. Possibly ditch Conda and Poetry and start using [PDM](https://pdm-project.org/en/latest/). For now, Python can also be installed via the Conda environment instead of a local installation.

**Comment by JordiBolibar** [comment]
Have you tried using micromamba? That's what we use with ODINN and it's generally very fast, and it uses the same steps as with conda (i.e. simpler than with poetry).
