### ISSUE TITLE
OGGM datapulling not working

### ISSUE THREAD

**Issue by marvande** [ODINN-SciML/MassBalanceMachine#46]
@JulianBiesheuvel I tried to run the `data_processing_wgms.ipynb` notebook but the oggm pipeline does not work: `ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject`

For now I've done it manually for CH in another notebook. But maybe you could have a look? 

Note: I think it might be an environment problem because I have a separate env. for oggm notebooks and when I try to run it in the MassBalanceMachine env. the issue pops up.

**Comment by JulianBiesheuvel** [comment]
Might have fixed it based on this [StackOverflow Thread](https://stackoverflow.com/questions/78634235/numpy-dtype-size-changed-may-indicate-binary-incompatibility-expected-96-from), by downgrading the Numpy version to 1.26.0.
